
import Head from "next/head";
import{FiMenu} from "react-icons/fi"
import ScrollToTop from "react-scroll-to-top"
import{FaChevronCircleUp} from "react-icons/fa"
import {
  SiTailwindcss,
  SiAdobephotoshop,
  SiAdobeillustrator,
  SiAdobeindesign,
  SiFigma,
  SiFirebase,
  SiTypescript,
  SiJest,
  SiJasmine,
} from "react-icons/si";
import {
  DiAngularSimple,
  DiCss3,
  DiScrum,
  DiGit,
  DiGithubBadge,
  DiHtml5,
  DiJavascript,
  DiNodejs,
  DiVisualstudio,
} from "react-icons/di";
import {
  AiFillLinkedin,
  AiFillMail,
  AiFillGithub,
} from "react-icons/ai";
import karla from "../public/karla.png";
import design from "../public/design.png";
import code from "../public/code.png";
import scrum from "../public/scrum.jpg";
import Image from "next/image";
import cipher from "../public/cipher.png";
import data from "../public/dataLovers.png";
import sn from "../public/sn.png";
import md from "../public/mdLinks.png";
import bq from "../public/burger.png";
import abr from "../public/abraxas.png";
import { useState } from "react";
import Link from "next/link";


export default function Home() {
  const [open, setOpen] = useState(false)

  return (
    < div>
      <Head>
        <title className="text-[0.6rem]">karla portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main className="w-screen flex flex-col mx-auto">
      <ScrollToTop smooth color="#6f00ff" component={<p style={{ color: "teal" }}>👆</p>} />
        <header className=" bg-teal-600 bg-opacity-80 boder-bpy-2 w-full fixed z-20 top-0 left-0">
          <div className="flex items-center  boder-b  py-2 w-full  justify-between px-[8%] max-w-full xl:max-w-7xl  xl:mx-auto flex-wrap ">
            <span className="flex gap-1 items-center ">
            <Image src={abr} alt="logo Karla" className="w-11" />
            <p className="text-4xl text-[#f5f5f5] bg- font-normal font-enchanted ">Abraxas</p>
            </span>
            <FiMenu className="md:hidden block h-6 w-6 cursor-pointer text-[#edf2f4]" onClick={() => setOpen(!open)} />
            <nav className={`${open ? "block" : "hidden"} w-full md:flex items-center md:w-auto`}>
              <ul className="text-base text-[#f5f5f5] md:flex md:justify-between ">
                <li>
                  <a className="md:px-5 py-2 block hover:text-[#f8e36e] font-semibold" href="#home" onClick={() => setOpen(!open)} >Home</a>
                </li>
                <li>
                  <a className="md:px-5 py-2 block hover:text-[#f8e36e] font-semibold" href="#about" onClick={() => setOpen(!open)}>About</a>
                </li>
                <li>
                  <a className="md:px-5 py-2 block hover:text-[#f8e36e] font-semibold" href="#proyect" onClick={() => setOpen(!open)}>Projects</a>
                </li>
                <li>
                  <Link className="md:px-5 py-2 block text-gray-800 bg-gradient-to-t from-[#ffee88] to-[#f8e36e] hover:from-teal-400 hover:to-teal-700 hover:text-white font-medium rounded-lg text-sm px-5 text-center mr-3 md:mr-0 h-auto w-auto " href="cvKarla.pdf" download={"cvKarla.pdf"}>Resume</Link>
                </li>
              </ul>
            </nav>
          </div>
        </header>
        <section id="home" className="min-h-screen flex flex-col bg-[url('../public/miranda.png')] bg-cover lg:flex-row lg:w-full  lg:mx-auto lg:items-center lg:my-0">
          <div className="text-center px-6 pt-10 pb-5 md:pt-0  lg:mt-20 mt-20 lg:px-12">
            <h2 className="text-3xl py-2 text-[#edf2f4] font-medium md:text-5xl">
              Hello! I&apos;m
              <span className=" font-extrabold text-[#ffee88]">
              &nbsp;Karla Rodríguez
              </span>
              , <br></br>but you can call me
              <p className=" text-[#ffee88] text-9xl mt-4 font-enchanted md:text-12xl lg:text-18xl font-normal">
                Abraxas
              </p>
            </h2>
            <h3 className="text-xl py-2 pl-4 pr-4 md:text-1xl  sm:max-w-xl lg:max-w-2xl mx-auto text-center  text-[#edf2f4]">
              
              I&apos;m a <strong>Web Developer</strong>,
              <strong>&nbsp;Graphic Designer</strong> and <strong> tattooist</strong> 
              &nbsp;based in Mexico City. I&apos;m currently focused on Angular, Typescript and in continuous learning.
            </h3>
            <div className="text-3xl flex justify-center gap-16 py-3 text-[#ffee88] md:text-5xl">
            <a className="cursor-pointer" href="https://github.com/karlaCRM"><AiFillGithub /></a>
            <a className="cursor-pointer" href="https://www.linkedin.com/in/karla-cecilia-rm/"><AiFillLinkedin /></a>
            <a className="cursor-pointer" href="mailto:abraxaskrm@gmail.com"><AiFillMail /></a>
          </div>
          </div>
          <div className=" relative  mt-0 mx-auto overflow-hidden w-60 h-50 fill  lg:w-80 lg:h-auto lg:fill mb-11">
            <Image src={karla}
                alt="karla"
                width={280}
                height={280}
                />
          </div>
         
        </section>
        <section id="about" className="min-h-screen bg-gradient-to-l from-gray-200 to-gray-100 px-6 md:pb-12 ">
          <br></br>
          
          <div className="flex flex-col pt-10 pb-5  md:pt-0  lg:mt-20 mt-6 items-center pl-6 pr-9">
            <h3 className="text-3xl py-1 font-bold text-[#dd2d4a] md:text-4xl">ABOUT ME</h3>
            <p className="text-md py-2 leading-8 text-gray-800 text-justify md:text-md max-w-2xl ">
              I like to consider myself an artisan. Everything I have learned
              has been driven by the desire to &quot;create&quot;, to
              materialize my ideas and be able to share them with others. Each
              line drawn with the machine, each vector created in Illustrator is
              a form of self-expression focused on a client, and truly, I
              promise you... there is nothing more beautiful than knowing that
              you have made someone happy by giving them what they need.
              <span className=" text-[#dd2d4a] font-semibold">
              &nbsp;For me Frontend development is a simile because in each project
                I&apos;m creating from scratch and materializing through myself,
                a product that will be used by others.
              </span>
            </p>
          </div>
          <div className="flex flex-col items-center lg:flex-row gap-2 w-[90%] mx-auto lg:gap-5 lg:justify-around lg:px-12 pb-8 lg:items-stretch ">
            <div className="text-center flex flex-col align-middle shadow-lg shadow-gray-500 p-10 w-fit rounded-xl my-2 bg-neutral-50 lg:w-1/3">
              <Image
                src={design}
                alt="design"
                width={100}
                height={100}
                className="self-center"
              />
              <h3 className="text-base font-bold pt-8 pb-2 md:text-xl ">
                Beautiful Designs
              </h3>
              <p className="py-2 text-sm">
                
                Creating designs suited for your needs,<br></br> I am learning
                to use bootstrap and tailwindcss
              </p>
              <h4 className="py-4 text-teal-600 font-bold">
                Design tools I use
              </h4>
              <div className="flex justify-center flex-wrap gap-1 items-center">
                <SiAdobephotoshop className="text-3xl text-gray-800 mb-1 w-18 h-18" />
                <SiAdobeillustrator className="text-3xl  text-gray-800 mb-1 w-18 h-18" />
                <SiAdobeindesign className="text-3xl  text-gray-800 mb-1 w-18 h-18" />
                <SiFigma className="text-3xl  text-gray-800 mb-1 w-18 h-18" />
                <SiTailwindcss className="text-3xl  text-gray-800 mb-1 w-18 h-18" />
              </div>
            </div>
            <div className="text-center flex flex-col align-middle shadow-lg shadow-gray-500 p-10 w-fit rounded-xl my-2 bg-neutral-50 lg:w-1/3">
              <Image
                src={code}
                alt="code"
                width={100}
                height={100}
                className="self-center"
              />
              <h3 className="text-base font-bold pt-8 pb-2 md:text-xl">
                
                Coding your needs
              </h3>
              <p className="py-2 text-sm  max-w-sm">
                
                I am in a continuous learning process, I am currently learning
                Angular and Typescript
              </p>
              <h4 className="py-4 text-teal-600 font-bold">
                Dev tools I use
              </h4>
              <div className="flex justify-center flex-wrap gap-1 items-center">
                <SiFirebase className="text-3xl text-gray-800 mb-1 " />
                <SiJest className="text-3xl  text-gray-800 mb-1 " />
                <SiTypescript className="text-3xl  text-gray-800 mb-1 " />
                <DiAngularSimple className="text-3xl  text-gray-800 mb-1 " />
                <DiCss3 className="text-3xl  text-gray-800 mb-1 " />
                <DiHtml5 className="text-3xl  text-gray-800 mb-1 " />
                <DiJavascript className="text-3xl  text-gray-800 mb-1 " />
                <DiNodejs className="text-3xl  text-gray-800 mb-1 " />
                <DiVisualstudio className="text-4xl  text-gray-800 mb-1 " />
              </div>
            </div>
            <div className="text-center flex flex-col align-middle shadow-lg shadow-gray-500 p-10 w-fit rounded-xl my-2 bg-neutral-50 lg:w-1/3" >
              <Image
                src={scrum}
                alt="design"
                width={100}
                height={100}
                className="self-center"
              />
              <h3 className="text-base font-bold pt-8 pb-2 md:text-xl">
                Collaborative work skills
              </h3>
              <p className="py-2 text-sm">
                Work development following Agile methodologies
              </p>
              <h4 className="py-4 text-teal-600 font-bold">Tools:</h4>
              <div className="flex justify-center flex-wrap gap-1 items-center">
                <DiScrum className="text-5xl text-gray-800 mb-1 " />
                <DiGit className="text-5xl  text-gray-800 mb-1" />
                <DiGithubBadge className="text-5xl  text-gray-800 mb-1" />
              </div>
            </div>
           
          </div>
         
        </section>
        <section id="proyect" className=" bg-[url('../public/mirandaVer.png')] bg-contain md:bg-cover flex mx-auto justify-center w-full" >
          <div className='min-h-screen   md:bg-[#a4133c]  sm:bg-opacity-0 md:w-2/3 pb-10'>
          <br></br>
          <div className="flex flex-col pt-10 pb-5  md:pt-0  md:mt-20 mt-6 items-center px-5 ">
            <h3 className="text-3xl py-1 font-bold text-[#edf2f4] md:text-4xl pb-3 tracking-wide">PROJECTS</h3>
            <p className="text-md py-2 leading-8 text-[#edf2f4] text-center md:text-lg max-w-md">
              Here are some of the projects I&apos;ve done and that{" "}
              <span className=" text-[#f8e36e] font-semibold">
                you can find on my GitHub:
              </span>
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 px-6 w-full place-content-center gap-3 sm:px-12 md:px-10">
            <div className="grid grid-flow-col grid-cols-1 bg-white bg-opacity-90 px-5 lg:px-2 py-4 rounded-lg w-full place-content-start">
          <a href="https://github.com/karlaCRM/DEV001-cipher-karlaCRM.github.io">
            <Image src={cipher} alt="cipher project" className="mb-2 rounded-md"/>
            <h3 className="text-sm text-center font-extrabold   text-[#a4133c]">Cipher</h3>
            <p className="text-xs text-center font-semibold px-2 mb-2">Users can encrypt and decrypt a message using caesar encryption.</p>
            <h4 className="text-xs text-center font-bold px-2  text-teal-700 mb-2">Dev Learning Goals</h4>
            <div className="grid  grid-cols-4 text-3xl md:text-2xl px-2 gap-2 grid-flow-row place-items-center">
              <DiHtml5 />
              <DiCss3 />
              <DiJavascript />
              <DiGit />
            </div>
            </a>
            </div>
            <div className="grid grid-flow-col grid-cols-1 bg-white bg-opacity-90 px-5 lg:px-2 py-4 rounded-lg w-full place-content-start">
          <a href="https://github.com/karlaCRM/Data-lovers-PokeLab-karla">
            <Image src={data} alt="datalovers project" className="mb-2 rounded-md"/>
            <h3 className="text-sm text-center font-extrabold   text-[#a4133c]">DataLovers</h3>
            <p className="text-xs text-center font-semibold px-2 mb-2"> Page that allows you to view, filter and sort data about pokemon.</p>
            <h4 className="text-xs text-center font-bold px-2  text-teal-700 mb-2">Dev Learning Goals</h4>
            <div className="grid  grid-cols-6 text-3xl  md:text-2xl px-2 gap-2 grid-flow-row place-items-center ">
              <DiHtml5 />
              <DiCss3 />
              <DiJavascript />
              <DiGit />
              <DiScrum />
              <SiFigma />
              <DiGithubBadge className="col-start-3"/>
              <SiJest />
            </div>
            </a>
            </div>
            <div className="grid grid-flow-col grid-cols-1 bg-white bg-opacity-90 px-5 lg:px-2 py-4 rounded-lg w-full place-content-start">
          <a href="https://github.com/karlaCRM/DEV001-social-network-SN01">
            <Image src={sn} alt="social network project" className="mb-2 rounded-md"/>
            <h3 className="text-sm text-center font-extrabold   text-[#a4133c]">PawsFinder Social Network</h3>
            <p className="text-xs text-center font-semibold px-2 mb-2">Social network for animal lovers, allows you to create, edit and delete posts.</p>
            <h4 className="text-xs text-center font-bold px-2  text-teal-700 mb-2">Dev Learning Goals</h4>
            <div className="grid  grid-cols-6 text-3xl md:text-2xl px-2 gap-2 grid-flow-row place-items-center">
            <DiHtml5 />
              <DiCss3 />
              <DiJavascript />
              <DiGit />
              <DiScrum />
              <SiFigma />
              <DiGithubBadge/>
              <SiFirebase />
              <SiJest />
            </div>
            </a>
            </div>
            <div className="grid grid-flow-col grid-cols-1 bg-white bg-opacity-90 px-5 lg:px-2 py-4 rounded-lg w-full place-content-start">
          <a href="https://github.com/karlaCRM/md-links-KarlaCRM">
            <Image src={md} alt="mdlinks project" className="mb-2 rounded-md"/>
            <h3 className="text-sm text-center font-extrabold   text-[#a4133c]">MdLinks</h3>
            <p className="text-xs text-center font-semibold px-2 mb-2">
Created with NodeJs, it allows to find and validate links inside .md files, it also finds .md files inside directories and extracts links.</p>
            <h4 className="text-xs text-center font-bold px-2  text-teal-700 mb-2">Dev Learning Goals</h4>
            <div className="grid  grid-cols-5 text-3xl md:text-2xl px-2 gap-2 grid-flow-row place-items-center">
              <DiJavascript />
              <DiGit />
              <DiScrum />
              <DiGithubBadge />
              <SiJest />
              <DiNodejs className=" text-4xl col-span-5" />
            </div>
            </a>
            </div>
            <div className="grid grid-flow-col grid-cols-1 bg-white bg-opacity-90 px-5 lg:px-2 py-4 rounded-lg w-full place-content-start">
          <a href="https://github.com/karlaCRM/DEV001-burger-queen-api-client-KarlaCRM">
            <Image src={bq} alt="burger project" className="mb-2 rounded-md"/>
            <h3 className="text-sm text-center font-extrabold   text-[#a4133c]">Burger Queen Api Client</h3>
            <p className="text-xs text-center font-semibold px-2 mb-2"><strong>In process. </strong>Interface created for a fast food restaurant. Employees can take orders, send them to the kitchen, and have more control over products and prices.</p>
            <h4 className="text-xs text-center font-bold px-2  text-teal-700 mb-2">Dev Learning Goals</h4>
            <div className="grid  grid-cols-6 text-3xl md:text-2xl px-2 gap-2 grid-flow-row place-items-center place">
              <DiHtml5 />
              <DiCss3 />
              <DiJavascript />
              <DiGit />
              <DiScrum />
              <SiJasmine />
              <DiGithubBadge />
              <SiJest />
              <DiAngularSimple />
              <SiTypescript />
            </div>
            </a>
            </div>
          </div>
          </div>
        </section>
      </main>
    </div>
  );
}
